spring:
  application:
    name: pooII
  datasource:
    url: jdbc:mysql://127.0.0.1:8080/PO_II_DATABASE
    username: POO_II_USER
    password: PO_II_PASSWORD123@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port : 8081