spring:
  application:
    name: pooII
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/PO_II_DATABASE}
    username: ${DB_USERNAME:POO_II_USER}
    password: ${DB_PASSWORD:PO_II_PASSWORD123@}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: ${PORT:8081}
